"""Add vendor deductions

Revision ID: ee101d14713a
Revises: 20260409_01
Create Date: 2026-04-10 10:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee101d14713a'
down_revision: Union[str, None] = '20260409_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE trip_vehicles
        ADD COLUMN IF NOT EXISTS vendor_deduction_description VARCHAR,
        ADD COLUMN IF NOT EXISTS vendor_deduction_amount FLOAT DEFAULT 0,
        ADD COLUMN IF NOT EXISTS vendor_deduction_note VARCHAR,
        ADD COLUMN IF NOT EXISTS vendor_deduction_vendor VARCHAR;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_vehicles', 'vendor_deduction_vendor')
    op.drop_column('trip_vehicles', 'vendor_deduction_note')
    op.drop_column('trip_vehicles', 'vendor_deduction_amount')
    op.drop_column('trip_vehicles', 'vendor_deduction_description')
    # ### end Alembic commands ###
